export enum ErrorCode {
  // Auth
  ORG_CREATE_FAILED = 'ORG_CREATE_FAILED',
  AUTH_SIGNUP_FAILED = 'AUTH_SIGNUP_FAILED',
  USER_CREATE_FAILED = 'USER_CREATE_FAILED',
  SIGNIN_FAILED = 'SIGNIN_FAILED',
  SIGNOUT_FAILED = 'SIGNOUT_FAILED',
  SESSION_ERROR = 'SESSION_ERROR',
  AUTH_ERROR = 'AUTH_ERROR',
  NO_USER = 'NO_USER',
  NO_ORG = 'NO_ORG',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  INVITE_FAILED = 'INVITE_FAILED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED',
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  SIGN_OUT_FAILED = 'SIGN_OUT_FAILED',

  // Organization
  ORG_NOT_FOUND = 'ORG_NOT_FOUND',
  MEMBERS_FETCH_FAILED = 'MEMBERS_FETCH_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  CANNOT_REMOVE_SELF = 'CANNOT_REMOVE_SELF',
  DELETE_FAILED = 'DELETE_FAILED',
  ORG_UPDATE_FAILED = 'ORG_UPDATE_FAILED',
  PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED',
  INVITES_FETCH_FAILED = 'INVITES_FETCH_FAILED',
  ALREADY_INVITED = 'ALREADY_INVITED',
  INVITE_CREATE_FAILED = 'INVITE_CREATE_FAILED',
  INVITE_REVOKE_FAILED = 'INVITE_REVOKE_FAILED',
  ROLE_UPDATE_FAILED = 'ROLE_UPDATE_FAILED',
  MEMBER_REMOVAL_FAILED = 'MEMBER_REMOVAL_FAILED',
  FORBIDDEN = 'FORBIDDEN',

  // Campaign
  CAMPAIGNS_FETCH_FAILED = 'CAMPAIGNS_FETCH_FAILED',
  STATS_FETCH_FAILED = 'STATS_FETCH_FAILED',
  CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  INVALID_LAUNCH_DATE = 'INVALID_LAUNCH_DATE',
  CAMPAIGN_CREATE_FAILED = 'CAMPAIGN_CREATE_FAILED',
  CAMPAIGN_UPDATE_FAILED = 'CAMPAIGN_UPDATE_FAILED',
  CAMPAIGN_DELETE_FAILED = 'CAMPAIGN_DELETE_FAILED',

  // Task
  TASKS_FETCH_FAILED = 'TASKS_FETCH_FAILED',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  INVALID_DEPENDENCY = 'INVALID_DEPENDENCY',
  TASK_CREATE_FAILED = 'TASK_CREATE_FAILED',
  INVALID_TRANSITION = 'INVALID_TRANSITION',
  DEPENDENCY_NOT_MET = 'DEPENDENCY_NOT_MET',
  TASK_UPDATE_FAILED = 'TASK_UPDATE_FAILED',
  TASK_DELETE_FAILED = 'TASK_DELETE_FAILED',

  // Dashboard
  METRICS_FETCH_FAILED = 'METRICS_FETCH_FAILED',
  ALERTS_FETCH_FAILED = 'ALERTS_FETCH_FAILED',

  // Notification
  NOTIFICATIONS_FETCH_FAILED = 'NOTIFICATIONS_FETCH_FAILED',
  NOTIFICATION_UPDATE_FAILED = 'NOTIFICATION_UPDATE_FAILED',
  NOTIFICATION_CREATE_FAILED = 'NOTIFICATION_CREATE_FAILED',
  TOKEN_UPDATE_FAILED = 'TOKEN_UPDATE_FAILED',

  // Escalation
  INVALID_STAGE = 'INVALID_STAGE',
  ESCALATIONS_FETCH_FAILED = 'ESCALATIONS_FETCH_FAILED',

  // Client
  CLIENTS_FETCH_FAILED = 'CLIENTS_FETCH_FAILED',
  NAME_EXISTS = 'NAME_EXISTS',
  CLIENT_CREATE_FAILED = 'CLIENT_CREATE_FAILED',

  // Validation
  MISSING_FIELDS = 'MISSING_FIELDS',
  MISSING_NAME = 'MISSING_NAME',
  INVALID_ROLE = 'INVALID_ROLE',
  MISSING_STATUS = 'MISSING_STATUS',
  INVALID_STATUS = 'INVALID_STATUS',
  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_RISK_FLAG = 'INVALID_RISK_FLAG',
  MISSING_ROLE = 'MISSING_ROLE',

  // System
  NETWORK_ERROR = 'NETWORK_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}